"""add insight sessions and messages, job triggered_by

Revision ID: 0f39b4657605
Revises: a7fd115058d7
Create Date: 2026-08-29 20:24:23.256973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f39b4657605'
down_revision: Union[str, Sequence[str], None] = 'a7fd115058d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('gathering', 'summarizing', 'ready', 'failed', name='insight_session_status'), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_sessions_created_at'), 'insight_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_insight_sessions_image_id'), 'insight_sessions', ['image_id'], unique=False)
    op.create_table('insight_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='insight_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('referenced_job_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['insight_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_messages_created_at'), 'insight_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_insight_messages_session_id'), 'insight_messages', ['session_id'], unique=False)
    # server_default required: existing rows need a value for this NOT NULL
    # column too, not just new ones (autogenerate doesn't add this on its own
    # from the Python-level `default=` - that only applies to inserts made
    # through this app, not to backfilling already-existing rows).
    op.add_column(
        'jobs', sa.Column('triggered_by', sa.String(), nullable=False, server_default='user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'triggered_by')
    op.drop_index(op.f('ix_insight_messages_session_id'), table_name='insight_messages')
    op.drop_index(op.f('ix_insight_messages_created_at'), table_name='insight_messages')
    op.drop_table('insight_messages')
    op.drop_index(op.f('ix_insight_sessions_image_id'), table_name='insight_sessions')
    op.drop_index(op.f('ix_insight_sessions_created_at'), table_name='insight_sessions')
    op.drop_table('insight_sessions')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop the Postgres ENUM types created for these
    # columns (see the identical gotcha fixed in 3fb644e16b27) - without
    # this, re-running upgrade() after a downgrade fails with "type already
    # exists".
    sa.Enum(name='insight_role').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='insight_session_status').drop(op.get_bind(), checkfirst=True)
