"""add image os_version

Revision ID: a7fd115058d7
Revises: 47b6ba380f48
Create Date: 2026-08-29 18:53:41.311528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fd115058d7'
down_revision: Union[str, Sequence[str], None] = '47b6ba380f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('os_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'os_version')
    # ### end Alembic commands ###
