"""add job engine and image legacy_profile

Revision ID: e996f9c0a648
Revises: 0f39b4657605
Create Date: 2026-08-30 17:01:30.110864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e996f9c0a648'
down_revision: Union[str, Sequence[str], None] = '0f39b4657605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('legacy_profile', sa.String(), nullable=True))
    # server_default required: existing rows need a value too, not just new
    # ones (same gotcha as jobs.triggered_by in 0f39b4657605).
    op.add_column('jobs', sa.Column('engine', sa.String(), nullable=False, server_default='v3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'engine')
    op.drop_column('images', 'legacy_profile')
    # ### end Alembic commands ###
